# Generated by Django 3.0.3 on 2020-06-27 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itself_news',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
