# Generated by Django 3.0.3 on 2020-07-01 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_itself_news_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='itself_news',
            name='event_place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
