# Generated by Django 3.0.3 on 2020-07-06 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_itself_news_event_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itself_news',
            name='brief_description',
        ),
    ]
