# Generated by Django 3.0.3 on 2020-07-01 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='covid_news',
            name='published_other_date',
        ),
        migrations.AddField(
            model_name='covid_news',
            name='event_place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='covid_news',
            name='published_at',
            field=models.DateTimeField(),
        ),
    ]
