# Generated by Django 3.0.3 on 2020-07-06 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0004_remove_covid_news_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covid_news',
            name='published_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
