# Generated by Django 3.0.3 on 2020-07-01 04:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_auto_20200701_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business_news',
            name='published_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
