# Generated by Django 3.0.3 on 2020-07-01 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_auto_20200701_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business_news',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='business_news',
            name='updated_at',
        ),
    ]
