# Generated by Django 3.0.3 on 2020-07-01 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0002_auto_20200701_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tech_news',
            name='published_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
