# Generated by Django 3.0.3 on 2020-07-06 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0004_remove_tech_news_brief_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tech_news',
            name='position',
        ),
        migrations.RemoveField(
            model_name='tech_news',
            name='published_other_date',
        ),
    ]
