# Generated by Django 3.0.3 on 2020-07-06 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lifestyle', '0002_lifestyle_news_event_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lifestyle_news',
            name='brief_description',
        ),
    ]
