# Generated by Django 3.0.3 on 2020-07-06 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entertainment_news',
            name='brief_description',
        ),
    ]
