# Generated by Django 3.0.3 on 2020-07-06 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0003_auto_20200706_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entertainment_news',
            name='published_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
