# Generated by Django 3.0.3 on 2020-06-20 10:22

from django.db import migrations, models
import newsportalapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=255)),
                ('reporter', models.CharField(blank=True, max_length=50, null=True)),
                ('description_top', models.TextField()),
                ('description_center', models.TextField()),
                ('description_bottom', models.TextField()),
                ('picture_top', models.ImageField(blank=True, null=True, upload_to=newsportalapp.models.upload_location)),
                ('picture_right', models.ImageField(blank=True, null=True, upload_to=newsportalapp.models.upload_location)),
                ('picture_bottom', models.ImageField(blank=True, null=True, upload_to=newsportalapp.models.upload_location)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=newsportalapp.models.upload_location)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
