# Generated by Django 3.0.3 on 2020-06-25 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsportalapp', '0003_news_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='event_place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
