# Generated by Django 3.0.3 on 2020-06-27 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsportalapp', '0005_news_featured'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='description_bottom',
            new_name='brief_description',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='description_center',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='picture_bottom',
            new_name='picture1',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='picture_right',
            new_name='picture2',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='picture_top',
            new_name='picture3',
        ),
        migrations.RemoveField(
            model_name='news',
            name='description_top',
        ),
        migrations.AddField(
            model_name='news',
            name='published_other_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='published_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
