# Generated by Django 3.0.3 on 2020-07-05 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsportalapp', '0006_auto_20200627_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='published_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
