# Generated by Django 3.0.3 on 2020-07-05 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsportalapp', '0007_auto_20200705_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='published_other_date',
        ),
    ]
