# Generated by Django 3.0.3 on 2020-07-06 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsportalapp', '0008_remove_news_published_other_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='brief_description',
        ),
    ]
