# Generated by Django 3.0.3 on 2020-07-06 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsportalapp', '0009_remove_news_brief_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='position',
        ),
    ]
