# Generated by Django 3.0.3 on 2020-07-06 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trending', '0002_auto_20200701_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trending_news',
            name='brief_description',
        ),
    ]
